[package]
name = "yalla"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.9.8"
anyhow = "1.0.101"
clap = { version = "4.5.57", features = ["derive"] }
shlex = "1.3.0"
tempfile = "3.24.0"

[dev-dependencies]
snapbox = "0.6.24"
trycmd = "1.0.0"

